# Generated by Django 5.1.2 on 2026-05-26 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.verse')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('days', models.IntegerField()),
                ('cover_image', models.ImageField(blank=True, upload_to='plans/')),
                ('verses', models.ManyToManyField(through='study.PlanDay', to='study.verse')),
            ],
        ),
        migrations.AddField(
            model_name='planday',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_days', to='study.readingplan'),
        ),
        migrations.CreateModel(
            name='UserPlanProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_day', models.IntegerField(default=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.readingplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
