# Generated by Django 5.1.2 on 2026-05-27 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_planday_readingplan_planday_plan_userplanprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDevotional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('theme', models.CharField(blank=True, max_length=100)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('reflection_prompt', models.TextField(blank=True)),
                ('prayer_request', models.TextField(blank=True)),
                ('published_date', models.DateField(db_index=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('key_verse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='study.verse')),
            ],
            options={
                'verbose_name_plural': 'Daily Devotionals',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='UserDevotionalProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('reflection_note', models.TextField(blank=True)),
                ('devotional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.dailydevotional')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devotional_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-read_at'],
                'unique_together': {('user', 'devotional')},
            },
        ),
    ]
