# Generated by Django 5.1.2 on 2026-05-27 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_dailydevotional_userdevotionalprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('abbreviation', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CrossReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('referenced_verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referenced_by', to='study.verse')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_references', to='study.verse')),
            ],
        ),
        migrations.CreateModel(
            name='VerseCommentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('cultural_context', models.TextField(blank=True)),
                ('theological_meaning', models.TextField(blank=True)),
                ('practical_application', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commentary', to='study.verse')),
            ],
            options={
                'verbose_name_plural': 'Verse Commentaries',
            },
        ),
        migrations.CreateModel(
            name='UserBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.verse')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'verse')},
            },
        ),
        migrations.CreateModel(
            name='UserHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('red', 'Red'), ('purple', 'Purple')], default='yellow', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to=settings.AUTH_USER_MODEL)),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.verse')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'verse')},
            },
        ),
        migrations.CreateModel(
            name='UserVerseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verse_notes', to=settings.AUTH_USER_MODEL)),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.verse')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'verse')},
            },
        ),
        migrations.CreateModel(
            name='VerseTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.translation')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='study.verse')),
            ],
            options={
                'unique_together': {('verse', 'translation')},
            },
        ),
    ]
