# Generated by Django 5.1.2 on 2026-05-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_translation_crossreference_versecommentary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='translation',
            field=models.CharField(default='KJV', max_length=10),
        ),
    ]
