# Generated by Django 5.1.2 on 2026-05-28 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_verse_translation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verse',
            name='text',
        ),
        migrations.RemoveField(
            model_name='verse',
            name='translation',
        ),
    ]
