# Generated by Django 5.1.2 on 2026-05-26 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_translation',
            field=models.CharField(choices=[('kjv', 'KJV'), ('niv', 'NIV'), ('nkjv', 'NKJV')], default='niv', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_xp',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_read_date', models.DateField(blank=True, null=True)),
                ('level', models.IntegerField(default=1)),
                ('xp_to_next_level', models.IntegerField(default=100)),
                ('total_verses_read', models.IntegerField(default=0)),
                ('total_insights_saved', models.IntegerField(default=0)),
                ('total_correct_quiz', models.IntegerField(default=0)),
                ('daily_reminder', models.BooleanField(default=False)),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('weekly_review', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
